exports.products = [
    {
        id: 1,
        name: 'C300 AMG',
        price: 90000,
        category: 'SEDAN',
        brand: 'MERCEDES',
        image1: '/assets/images/mer-c-300-amg.png',
        image2: '/assets/images/mer-c-300-amg-den.png',
        isNew: true,
        color: ['White', 'Black'],
        status:'..',
        description: 'Signs to identify a sedan based on its structure with three separate compartments: the engine compartment at the front (the hood), the passenger compartment (the body), and the luggage compartment at the rear (the trunk). In this arrangement, both the engine compartment and the luggage compartment are lower, while the passenger compartment is taller with two rows of seats. This design imparts a prestigious and luxurious appearance to the sedan. With a low chassis and good aerodynamic performance, sedan users can feel the smoothness when driving at high speeds. Moreover, sedans are also recognized for their solid handling, low noise levels, and minimal vibration.'
    },
    {
        id: 2,
        name: 'MAYBACH S450',
        price: 335000,
        category: 'SEDAN',
        brand: 'MERCEDES',
        image1: '/assets/images/mercedes-maybach-s-450-4matic-bac-iridium.png',
        image2: '/assets/images/mercedes-maybach-s-450-4matic-den.png',
        isNew: true,
        color: ['White', 'Black'],
        status:'..',
        description: 'Signs to identify a sedan based on its structure with three separate compartments: the engine compartment at the front (the hood), the passenger compartment (the body), and the luggage compartment at the rear (the trunk). In this arrangement, both the engine compartment and the luggage compartment are lower, while the passenger compartment is taller with two rows of seats. This design imparts a prestigious and luxurious appearance to the sedan. With a low chassis and good aerodynamic performance, sedan users can feel the smoothness when driving at high speeds. Moreover, sedans are also recognized for their solid handling, low noise levels, and minimal vibration.'
    },
    {
        id: 3,
        name: 'CIVIC RS',
        price: 35000,
        category: 'SEDAN',
        brand: 'HONDA',
        image1: '/assets/images/honda-civic-rs-trang.jpg',
        image2: '/assets/images/honda-civic-rs-do.jpg',
        isNew: true,
        color: ['White', 'Red'],
        status:'..',
        description: 'Signs to identify a sedan based on its structure with three separate compartments: the engine compartment at the front (the hood), the passenger compartment (the body), and the luggage compartment at the rear (the trunk). In this arrangement, both the engine compartment and the luggage compartment are lower, while the passenger compartment is taller with two rows of seats. This design imparts a prestigious and luxurious appearance to the sedan. With a low chassis and good aerodynamic performance, sedan users can feel the smoothness when driving at high speeds. Moreover, sedans are also recognized for their solid handling, low noise levels, and minimal vibration.'
    },
    {
        id: 4,
        name: 'CIVIC TypeR',
        price: 98000,
        category: 'SEDAN',
        brand: 'HONDA',
        image1: '/assets/images/honda-civic-typeR-trang.png',
        image2: '/assets/images/honda-civic-typeR-xanh.png',
        isNew: true,
        color: ['White', 'Blue'],
        status:'..',
        description: 'Signs to identify a sedan based on its structure with three separate compartments: the engine compartment at the front (the hood), the passenger compartment (the body), and the luggage compartment at the rear (the trunk). In this arrangement, both the engine compartment and the luggage compartment are lower, while the passenger compartment is taller with two rows of seats. This design imparts a prestigious and luxurious appearance to the sedan. With a low chassis and good aerodynamic performance, sedan users can feel the smoothness when driving at high speeds. Moreover, sedans are also recognized for their solid handling, low noise levels, and minimal vibration.'
    },
    {
        id: 5,
        name: 'CAMRY',
        price: 61000,
        category: 'SEDAN',
        brand: 'TOYOTA',
        image1: '/assets/images/toyota-camry-trang.png',
        image2: '/assets/images/toyota-camry-do.png',
        isNew: true,
        color: ['White', 'Red'],
        status:'..',
        description: 'Signs to identify a sedan based on its structure with three separate compartments: the engine compartment at the front (the hood), the passenger compartment (the body), and the luggage compartment at the rear (the trunk). In this arrangement, both the engine compartment and the luggage compartment are lower, while the passenger compartment is taller with two rows of seats. This design imparts a prestigious and luxurious appearance to the sedan. With a low chassis and good aerodynamic performance, sedan users can feel the smoothness when driving at high speeds. Moreover, sedans are also recognized for their solid handling, low noise levels, and minimal vibration.'
    },
    {
        id: 6,
        name: 'ES 250',
        price: 108000,
        category: 'SEDAN',
        brand: 'LEXUS',
        image1: '/assets/images/ES-250-trang.png',
        image2: '/assets/images/ES-250-den.jpg',
        isNew: true,
        color: ['White', 'Black'],
        status:'..',
        description: 'Signs to identify a sedan based on its structure with three separate compartments: the engine compartment at the front (the hood), the passenger compartment (the body), and the luggage compartment at the rear (the trunk). In this arrangement, both the engine compartment and the luggage compartment are lower, while the passenger compartment is taller with two rows of seats. This design imparts a prestigious and luxurious appearance to the sedan. With a low chassis and good aerodynamic performance, sedan users can feel the smoothness when driving at high speeds. Moreover, sedans are also recognized for their solid handling, low noise levels, and minimal vibration.'
    },
    {
        id: 7,
        name: 'YARIS 1.5G CVT',
        price: 28000,
        category: 'HATCHBACK',
        brand: 'TOYOTA',
        image1: '/assets/images/toyota-yaris-trang.png',
        image2: '/assets/images/toyota-yaris-den.png',
        isNew: true,
        color: ['White', 'Black'],
        status:'..',
        description:'The hatchback is a small or medium-sized car suitable for families needing extra luggage space. Its structure differs slightly from that of a sedan. In a hatchback, the rear end doesnt extend into a trunk; instead, it cuts straight at the back, creating a new door. This space can be folded down to create a very flexible storage area. Additionally, the ground clearance of this type of car is relatively high, aiding in swift movement and easy traversal of rough, muddy roads.'
    },
    {
        id: 8,
        name: 'RX 350',
        price: 140000,
        category: 'SUV',
        brand: 'LEXUS',
        image1: '/assets/images/RX-350-den.jpg',
        image2: '/assets/images/RX-350-xanh.jpg',
        isNew: true,
        color: ['Gray', 'Blue'],
        status:'..',
        description:'Possessing a rugged, sporty appearance, SUVs captivate automotive enthusiasts. This vehicle category features a frame designed separately based on the structure of pickup trucks. Its detachable undercarriage design, combined with powerful engines, delivers exceptional versatility and robust performance, ideal for off-road enthusiasts.Contemporary SUV models on the market are designed with seven spacious seats and five doors, making them suitable choices for family travel.'
    },
    {
        id: 9,
        name: 'LUX SA2.0',
        price: 58000,
        category: 'SUV',
        brand: 'VINFAST',
        image1: '/assets/images/lux-sa-m2-white.png',
        image2: '/assets/images/lux-sa-m2-blue.png',
        isNew: true,
        color: ['White', 'Blue'],
        status:'..',
        description:'Possessing a rugged, sporty appearance, SUVs captivate automotive enthusiasts. This vehicle category features a frame designed separately based on the structure of pickup trucks. Its detachable undercarriage design, combined with powerful engines, delivers exceptional versatility and robust performance, ideal for off-road enthusiasts.Contemporary SUV models on the market are designed with seven spacious seats and five doors, making them suitable choices for family travel.'
    },
    {
        id: 10,
        name: 'RANGER RAPOR',
        price: 53000,
        category: 'PICK TRUCK',
        brand: 'FORD',
        image1: '/assets/images/ford-raptor-trang.jpg',
        image2: '/assets/images/ford-raptor-cam.jpg',
        isNew: true,
        color: ['White', 'Orange'],
        status:'..',
        description:'The pickup truck is a vehicle that combines the characteristics of a small truck and a family car. True to its name, apart from the seating area, this type of vehicle is designed with a cargo bed at the rear, completely separate from the passenger compartment. Pickup trucks have the capability to transport large loads (typically ranging from 500 to 700 kg), a task that other car models find difficult to accomplish. Additionally, their chassis design resembles that of trucks, enabling them to navigate easily across various terrains. For users who frequently need to transport cargo but still want a vehicle suitable for family outings, a pickup truck is an optimal choice.'
    },
    {
        id: 11,
        name: 'HILUX',
        price: 37000,
        category: 'PICK TRUCK',
        brand: 'TOYOTA',
        image1: '/assets/images/hilux-trang.png',
        image2: '/assets/images/hilux-do.png',
        isNew: true,
        color: ['White', 'Red'],
        status:'..',
        description:'The pickup truck is a vehicle that combines the characteristics of a small truck and a family car. True to its name, apart from the seating area, this type of vehicle is designed with a cargo bed at the rear, completely separate from the passenger compartment. Pickup trucks have the capability to transport large loads (typically ranging from 500 to 700 kg), a task that other car models find difficult to accomplish. Additionally, their chassis design resembles that of trucks, enabling them to navigate easily across various terrains. For users who frequently need to transport cargo but still want a vehicle suitable for family outings, a pickup truck is an optimal choice.'

    },
    {
        id: 12,
        name: 'BT 50',
        price: 26000,
        category: 'PICK TRUCK',
        brand: 'MAZDA',
        image1: '/assets/images/bt-50-trang.png',
        image2: '/assets/images/bt-50-do.png',
        isNew: true,
        color: ['White', 'Red'],
        status:'..',
        description:'The pickup truck is a vehicle that combines the characteristics of a small truck and a family car. True to its name, apart from the seating area, this type of vehicle is designed with a cargo bed at the rear, completely separate from the passenger compartment. Pickup trucks have the capability to transport large loads (typically ranging from 500 to 700 kg), a task that other car models find difficult to accomplish. Additionally, their chassis design resembles that of trucks, enabling them to navigate easily across various terrains. For users who frequently need to transport cargo but still want a vehicle suitable for family outings, a pickup truck is an optimal choice.'

    },
    {
        id: 13,
        name: 'MAZDA 3',
        price: 30000,
        category: 'SEDAN',
        brand: 'MAZDA',
        image1: '/assets/images/mazda-3-trang.png',
        image2: '/assets/images/mazda-3-den.png',
        isNew: true,
        color: ['White', 'Black'],
        status:'..',
        description: 'Signs to identify a sedan based on its structure with three separate compartments: the engine compartment at the front (the hood), the passenger compartment (the body), and the luggage compartment at the rear (the trunk). In this arrangement, both the engine compartment and the luggage compartment are lower, while the passenger compartment is taller with two rows of seats. This design imparts a prestigious and luxurious appearance to the sedan. With a low chassis and good aerodynamic performance, sedan users can feel the smoothness when driving at high speeds. Moreover, sedans are also recognized for their solid handling, low noise levels, and minimal vibration.'
    },
    {
        id: 14,
        name: 'MAZDA CX-8',
        price: 52000,
        category: 'SUV',
        brand: 'MAZDA',
        image1: '/assets/images/mazda-cx-8-xam.jpg',
        image2: '/assets/images/mazda-cx8-nau.jpg',
        isNew: true,
        color: ['Gray', 'Brown'],
        status:'..',
        description:'Possessing a rugged, sporty appearance, SUVs captivate automotive enthusiasts. This vehicle category features a frame designed separately based on the structure of pickup trucks. Its detachable undercarriage design, combined with powerful engines, delivers exceptional versatility and robust performance, ideal for off-road enthusiasts.Contemporary SUV models on the market are designed with seven spacious seats and five doors, making them suitable choices for family travel.'
    },
    {
        id: 15,
        name: 'MAZDA 6',
        price: 37000,
        category: 'SEDAN',
        brand: 'MAZDA',
        image1: '/assets/images/m6-do.png',
        image2: '/assets/images/m6-do.png',
        isNew: true,
        color: ['Red'],
        status:'..'
    },
    {
        id: 16,
        name: 'BMW 330i M Sport',
        price: 74000,
        category: 'SEDAN',
        brand: 'BMW',
        image1: '/assets/images/bmw-330i-trang.png',
        image2: '/assets/images/bmw-320i-xam.png',
        isNew: true,
        color: ['White', 'Gray'],
        status:'..',
        description: 'Signs to identify a sedan based on its structure with three separate compartments: the engine compartment at the front (the hood), the passenger compartment (the body), and the luggage compartment at the rear (the trunk). In this arrangement, both the engine compartment and the luggage compartment are lower, while the passenger compartment is taller with two rows of seats. This design imparts a prestigious and luxurious appearance to the sedan. With a low chassis and good aerodynamic performance, sedan users can feel the smoothness when driving at high speeds. Moreover, sedans are also recognized for their solid handling, low noise levels, and minimal vibration.'
    },
    {
        id: 17,
        name: 'BMW X3 20i M Sport',
        price: 78000,
        category: 'SUV',
        brand: 'BMW',
        image1: '/assets/images/bmw-x3-den.png',
        image2: '/assets/images/bmw-x3-nau.png',
        isNew: true,
        color: ['Black', 'Brown'],
        status:'..',
        description:'Possessing a rugged, sporty appearance, SUVs captivate automotive enthusiasts. This vehicle category features a frame designed separately based on the structure of pickup trucks. Its detachable undercarriage design, combined with powerful engines, delivers exceptional versatility and robust performance, ideal for off-road enthusiasts.Contemporary SUV models on the market are designed with seven spacious seats and five doors, making them suitable choices for family travel.'
    },
    {
        id: 18,
        name: 'CAYENNE S Coupé',
        price: 394000,
        category: 'COUPÉ',
        brand: 'PORSCHE',
        image1: '/assets/images/cayenne-coupe-white.png',
        image2: '/assets/images/cayenne-coupe-white.png',
        isNew: true,
        color: ['White'],
        status:'..',
        description:'When mentioning a coupe, it evokes a sporty car with a sleek and modern design. Sports cars are designed with two doors, two seats (or an additional two rear seats), a closed roof with a roofline extending down to the tail, and a short rear end. They use high-performance engines, lack the B-pillar to enhance smoothness, and minimize vibrations when driving at high speeds. Nowadays, some coupe models are designed with four doors, although they resemble sedans quite closely, so the concept of a four-door coupe is not yet widely recognized. Nonetheless, coupes are still considered one of the compact sports car categories with excellent performance.'
    },
    {
        id: 19,
        name: 'MACAN S',
        price: 180000,
        category: 'SUV',
        brand: 'PORSCHE',
        image1: '/assets/images/macan-s-white.png',
        image2: '/assets/images/macan-s-cam.png',
        isNew: true,
        color: ['White', 'Orange'],
        status:'..',
        description:'Possessing a rugged, sporty appearance, SUVs captivate automotive enthusiasts. This vehicle category features a frame designed separately based on the structure of pickup trucks. Its detachable undercarriage design, combined with powerful engines, delivers exceptional versatility and robust performance, ideal for off-road enthusiasts.Contemporary SUV models on the market are designed with seven spacious seats and five doors, making them suitable choices for family travel.'
    },
    {
        id: 20,
        name: 'VF9',
        price: 89000,
        category: 'SUV',
        brand: 'VINFAST',
        image1: '/assets/images/Vf9-white.webp',
        image2: '/assets/images/Vf9-black.webp',
        isNew: true,
        color: ['White', 'Black'],
        status:'..',
        description:'Possessing a rugged, sporty appearance, SUVs captivate automotive enthusiasts. This vehicle category features a frame designed separately based on the structure of pickup trucks. Its detachable undercarriage design, combined with powerful engines, delivers exceptional versatility and robust performance, ideal for off-road enthusiasts.Contemporary SUV models on the market are designed with seven spacious seats and five doors, making them suitable choices for family travel.'
    },
    {
        id: 21,
        name: 'E300 AMG',
        price: 131000,
        category: 'SEDAN',
        brand: 'MERCEDES',
        image1: '/assets/images/e300-trang.png',
        image2: '/assets/images/e300-den.png',
        isNew: true,
        color: ['White', 'Black'],
        status:'..',
        description: 'Signs to identify a sedan based on its structure with three separate compartments: the engine compartment at the front (the hood), the passenger compartment (the body), and the luggage compartment at the rear (the trunk). In this arrangement, both the engine compartment and the luggage compartment are lower, while the passenger compartment is taller with two rows of seats. This design imparts a prestigious and luxurious appearance to the sedan. With a low chassis and good aerodynamic performance, sedan users can feel the smoothness when driving at high speeds. Moreover, sedans are also recognized for their solid handling, low noise levels, and minimal vibration.'
    },
    {
        id: 22,
        name: 'AUDI A8 L',
        price: 270000,
        category: 'SEDAN',
        brand: 'AUDI',
        image1: '/assets/images/A8-L-White.png',
        image2: '/assets/images/A8-L-Gray.png',
        isNew: true,
        color: ['White', 'Gray'],
        status:'..',
        description: 'Signs to identify a sedan based on its structure with three separate compartments: the engine compartment at the front (the hood), the passenger compartment (the body), and the luggage compartment at the rear (the trunk). In this arrangement, both the engine compartment and the luggage compartment are lower, while the passenger compartment is taller with two rows of seats. This design imparts a prestigious and luxurious appearance to the sedan. With a low chassis and good aerodynamic performance, sedan users can feel the smoothness when driving at high speeds. Moreover, sedans are also recognized for their solid handling, low noise levels, and minimal vibration.'
    },
    {
        id: 23,
        name: 'Kia K5 2.5 GT-LINE',
        price: 50000,
        category: 'SEDAN',
        brand: 'KIA',
        image1: '/assets/images/k5-trang.png',
        image2: '/assets/images/k5-xam.png',
        isNew: true,
        color: ['White', 'Gray'],
        status:'..',
        description: 'Signs to identify a sedan based on its structure with three separate compartments: the engine compartment at the front (the hood), the passenger compartment (the body), and the luggage compartment at the rear (the trunk). In this arrangement, both the engine compartment and the luggage compartment are lower, while the passenger compartment is taller with two rows of seats. This design imparts a prestigious and luxurious appearance to the sedan. With a low chassis and good aerodynamic performance, sedan users can feel the smoothness when driving at high speeds. Moreover, sedans are also recognized for their solid handling, low noise levels, and minimal vibration.'
    },
    {
        id: 24,
        name: 'CARNIVAL 3.5G SIGNATURE',
        price: 74000,
        category: 'SUV',
        brand: 'KIA',
        image1: '/assets/images/carnival-trang.png',
        image2: '/assets/images/carnival-xam.png',
        isNew: true,
        color: ['White', 'Gray'],
        status:'..',
        description:'Possessing a rugged, sporty appearance, SUVs captivate automotive enthusiasts. This vehicle category features a frame designed separately based on the structure of pickup trucks. Its detachable undercarriage design, combined with powerful engines, delivers exceptional versatility and robust performance, ideal for off-road enthusiasts.Contemporary SUV models on the market are designed with seven spacious seats and five doors, making them suitable choices for family travel.'
    },
    {
        id: 25,
        name: 'KIA K3 1.6 Turbo GT',
        price: 29000,
        category: 'SEDAN',
        brand: 'KIA',
        image1: '/assets/images/kia-k3-gt-line.png',
        image2: '/assets/images/kia-k3-gt-line.png',
        isNew: true,
        color: ['White'],
        status:'..',
        description: 'Signs to identify a sedan based on its structure with three separate compartments: the engine compartment at the front (the hood), the passenger compartment (the body), and the luggage compartment at the rear (the trunk). In this arrangement, both the engine compartment and the luggage compartment are lower, while the passenger compartment is taller with two rows of seats. This design imparts a prestigious and luxurious appearance to the sedan. With a low chassis and good aerodynamic performance, sedan users can feel the smoothness when driving at high speeds. Moreover, sedans are also recognized for their solid handling, low noise levels, and minimal vibration.'
    },
    {
        id: 26,
        name: 'MAZDA 3',
        price: 20000,
        category: 'HATCHBACK',
        brand: 'MAZDA',
        image1: '/assets/images/mazda-3-HATCHBACK-xanh.png',
        image2: '/assets/images/mazda-3-HATCHBACK-xanh.png',
        isNew: false,
        color: ['White', 'Black'],
        status:'..',
        description:'The hatchback is a small or medium-sized car suitable for families needing extra luggage space. Its structure differs slightly from that of a sedan. In a hatchback, the rear end doesnt extend into a trunk; instead, it cuts straight at the back, creating a new door. This space can be folded down to create a very flexible storage area. Additionally, the ground clearance of this type of car is relatively high, aiding in swift movement and easy traversal of rough, muddy roads.'

    },
    {
        id: 29,
        name: 'SANTAFE PREMIUM',
        price: 35000,
        category: 'SUV',
        brand: 'HUYNHDAI',
        image1: '/assets/images/Santafe_2021.png',
        image2: '/assets/images/Santafe_2021.png',
        isNew: false,
        color: ['White'],
        status:'..',
        description:'Possessing a rugged, sporty appearance, SUVs captivate automotive enthusiasts. This vehicle category features a frame designed separately based on the structure of pickup trucks. Its detachable undercarriage design, combined with powerful engines, delivers exceptional versatility and robust performance, ideal for off-road enthusiasts.Contemporary SUV models on the market are designed with seven spacious seats and five doors, making them suitable choices for family travel.'

    },
    {
        id: 30,
        name: 'TUCSON 2.0',
        price: 28000,
        category: 'SUV',
        brand: 'HUYNHDAI',
        image1: '/assets/images/tucson-2.0.png',
        image2: '/assets/images/tucson-2.0.png',
        isNew: false,
        color: ['Black'],
        status:'..',
        description:'Possessing a rugged, sporty appearance, SUVs captivate automotive enthusiasts. This vehicle category features a frame designed separately based on the structure of pickup trucks. Its detachable undercarriage design, combined with powerful engines, delivers exceptional versatility and robust performance, ideal for off-road enthusiasts.Contemporary SUV models on the market are designed with seven spacious seats and five doors, making them suitable choices for family travel.'

    },
    {
        id: 31,
        name: 'TRITON ATHLETE 4X2',
        price: 26000,
        category: 'PICK TRUCK',
        brand: 'MITSUBISHI',
        image1: '/assets/images/triton-4x2-at-athlete.png',
        image2: '/assets/images/triton-4x2-at-athlete.png',
        isNew: false,
        color: ['Red'],
        status:'..',
        description:'The pickup truck is a vehicle that combines the characteristics of a small truck and a family car. True to its name, apart from the seating area, this type of vehicle is designed with a cargo bed at the rear, completely separate from the passenger compartment. Pickup trucks have the capability to transport large loads (typically ranging from 500 to 700 kg), a task that other car models find difficult to accomplish. Additionally, their chassis design resembles that of trucks, enabling them to navigate easily across various terrains. For users who frequently need to transport cargo but still want a vehicle suitable for family outings, a pickup truck is an optimal choice.'

    },
    {
        id: 32,
        name: 'XPANDER',
        price: 19000,
        category: 'SUV',
        brand: 'MITSUBISHI',
        image1: '/assets/images/xpander-trang.png',
        image2: '/assets/images/xpander-trang.png',
        isNew: false,
        color: ['White'],
        status:'..',
        description:'Possessing a rugged, sporty appearance, SUVs captivate automotive enthusiasts. This vehicle category features a frame designed separately based on the structure of pickup trucks. Its detachable undercarriage design, combined with powerful engines, delivers exceptional versatility and robust performance, ideal for off-road enthusiasts.Contemporary SUV models on the market are designed with seven spacious seats and five doors, making them suitable choices for family travel.'

    },
    {
        id: 33,
        name: 'PEUGEOT 5008 GT-LINE',
        price: 40000,
        category: 'SUV',
        brand: 'PEUGEOT',
        image1: '/assets/images/peugeot-5008.png',
        image2: '/assets/images/peugeot-5008.png',
        isNew: false,
        color: ['Blue'],
        status:'..',
        description:'Possessing a rugged, sporty appearance, SUVs captivate automotive enthusiasts. This vehicle category features a frame designed separately based on the structure of pickup trucks. Its detachable undercarriage design, combined with powerful engines, delivers exceptional versatility and robust performance, ideal for off-road enthusiasts.Contemporary SUV models on the market are designed with seven spacious seats and five doors, making them suitable choices for family travel.'

    },
    {
        id: 34,
        name: 'PEUGEOT 3008 AL',
        price: 30000,
        category: 'SUV',
        brand: 'PEUGEOT',
        image1: '/assets/images/PEUGEOT-3008-TRANG.png',
        image2: '/assets/images/PEUGEOT-3008-TRANG.png',
        isNew: false,
        color: ['White'],
        status:'..',
        description:'Possessing a rugged, sporty appearance, SUVs captivate automotive enthusiasts. This vehicle category features a frame designed separately based on the structure of pickup trucks. Its detachable undercarriage design, combined with powerful engines, delivers exceptional versatility and robust performance, ideal for off-road enthusiasts.Contemporary SUV models on the market are designed with seven spacious seats and five doors, making them suitable choices for family travel.'

    },
    {
        id: 35,
        name: 'FORD TERRIORY TITANIUM',
        price: 34000,
        category: 'PICK TRUCK',
        brand: 'FORD',
        image1: '/assets/images/ford-territory-titanium.png',
        image2: '/assets/images/ford-territory-titanium.png',
        isNew: false,
        color: ['Red'],
        status:'..',
        description:'The pickup truck is a vehicle that combines the characteristics of a small truck and a family car. True to its name, apart from the seating area, this type of vehicle is designed with a cargo bed at the rear, completely separate from the passenger compartment. Pickup trucks have the capability to transport large loads (typically ranging from 500 to 700 kg), a task that other car models find difficult to accomplish. Additionally, their chassis design resembles that of trucks, enabling them to navigate easily across various terrains. For users who frequently need to transport cargo but still want a vehicle suitable for family outings, a pickup truck is an optimal choice.'

    },
    {
        id: 36,
        name: 'FORD EVEREST TITANIUM 4X4',
        price: 55000,
        category: 'PICK TRUCK',
        brand: 'FORD',
        image1: '/assets/images/everest-titanium.png',
        image2: '/assets/images/everest-titanium.png',
        isNew: false,
        color: ['Orange'],
        status:'..',
        description:'The pickup truck is a vehicle that combines the characteristics of a small truck and a family car. True to its name, apart from the seating area, this type of vehicle is designed with a cargo bed at the rear, completely separate from the passenger compartment. Pickup trucks have the capability to transport large loads (typically ranging from 500 to 700 kg), a task that other car models find difficult to accomplish. Additionally, their chassis design resembles that of trucks, enabling them to navigate easily across various terrains. For users who frequently need to transport cargo but still want a vehicle suitable for family outings, a pickup truck is an optimal choice.'

    },
    {
        id: 37,
        name: 'VinFast Fadil',
        price: 17000,
        category: 'HATCHBACK',
        brand: 'VINFAST',
        image1: '/assets/images/vinfast-fadil.png',
        image2: '/assets/images/vinfast-fadil.png',
        isNew: false,
        color: ['White'],
        status:'..',
        description:'The hatchback is a small or medium-sized car suitable for families needing extra luggage space. Its structure differs slightly from that of a sedan. In a hatchback, the rear end doesnt extend into a trunk; instead, it cuts straight at the back, creating a new door. This space can be folded down to create a very flexible storage area. Additionally, the ground clearance of this type of car is relatively high, aiding in swift movement and easy traversal of rough, muddy roads.'
    },

];

exports.categories = [
  { id: '1', category: 'SEDAN' },
  { id: '2', category: 'SUV' },
  { id: '3', category: 'COUPÉ' },
  { id: '4', category: 'PICK TRUCK' },
  { id: '5', category: 'HATCHBACK' },
];

exports.brands = [
    { id: '1', brand: 'MERCEDES' },
    { id: '2', brand: 'LEXUS' },
    { id: '3', brand: 'PORSCHE' },
    { id: '4', brand: 'FORD' },
    { id: '5', brand: 'MAZDA' },
    { id: '6', brand: 'KIA' },
    { id: '7', brand: 'HONDA' },
    { id: '8', brand: 'VINFAST' },
    { id: '9', brand: 'PEUGEOT' },
    { id: '10', brand: 'MITSUBISHI' },
    { id: '11', brand: 'HUYNHDAI' },
    { id: '12', brand: 'BMW' },
    { id: '13', brand: 'TOYOTA' },
    { id: '14', brand: 'AUDI' },
];

exports.users = [
    { id: 1, username: 'admin', password: 123456, img_src: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fuxwing.com%2Favatar-icon%2F&psig=AOvVaw2IMVQLIZ80PcRHml6-Cd0t&ust=1712421416511000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCMDLu4XBq4UDFQAAAAAdAAAAABAE" },
    { id: 2, username: 'manager', password: 111111, img_src: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fuxwing.com%2Favatar-icon%2F&psig=AOvVaw2IMVQLIZ80PcRHml6-Cd0t&ust=1712421416511000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCMDLu4XBq4UDFQAAAAAdAAAAABAE" },
];

exports.carts = [];

exports.orders = [];